#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
    external_bar all:35:0 \
    menubar_opacity 0.5 \
    mouse_follows_focus off \
    focus_follows_mouse off \
    display_arrangement_order default \
    window_origin_display default \
    window_placement second_child \
    window_zoom_persist on \
    window_shadow on \
    window_animation_duration 0.1 \
    window_animation_easing ease_out_expo \
    window_opacity_duration 0.2 \
    active_window_opacity 1.00 \
    normal_window_opacity 0.95 \
    window_opacity on \
    insert_feedback_color 0xffd75f5f \
    split_ratio 0.50 \
    split_type auto \
    auto_balance off \
    top_padding 03 \
    bottom_padding 03 \
    left_padding 03 \
    right_padding 03 \
    window_gap 03 \
    layout bsp \
    mouse_modifier alt \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# when window is dropped in center of another window, swap them (on edges it will split it)
echo "yabai configuration loaded.."
borders active_color=0xFFF2CDCD inactive_color=0xff494d64 width=5.0 &

